name: Build PDF

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run docker container
        run: |
          docker run --name hackmd2pdf hevgan/cts-inzynierka-md-latex-parser
          docker cp hackmd2pdf:~/inzynierka_in_container.pdf ./inzynierka.pdf
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: inzynierka
          path: ./inzynierka.pdf
      - name: Upload file to S3
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: './inzynierka.pdf'
          destination-dir: 'output'
